package com.scylladb.migrator.scylla

import java.nio.file.{ Files, Paths }

/** Describes a Cassandra version used as a migration source in integration tests.
  *
  * @param label
  *   Human-readable version label (e.g. "2.x")
  * @param port
  *   Host port mapped to the Docker container's CQL port (9042)
  * @param dockerHost
  *   Docker Compose service name used as the hostname in Spark config files
  */
case class CassandraVersion(label: String, port: Int, dockerHost: String)

object CassandraVersion {
  val V2 = CassandraVersion("2.x", 9046, "cassandra2")
  val V3 = CassandraVersion("3.x", 9045, "cassandra3")
  val V4 = CassandraVersion("4.x", 9043, "cassandra")
  val V5 = CassandraVersion("5.x", 9047, "cassandra5")

  /** Derive a version-specific Spark config file from a base config template.
    *
    * For the default source host ("cassandra", i.e. v4), the base file is returned as-is. For other
    * versions, a new file is generated by replacing `host: cassandra` in the source section with
    * the version's Docker hostname.
    */
  def configForSource(baseConfigFile: String, version: CassandraVersion): String = {
    if (version.dockerHost == "cassandra") return baseConfigFile

    val configDir = Paths.get("src", "test", "configurations")
    val baseContent = new String(Files.readAllBytes(configDir.resolve(baseConfigFile)))

    // Only replace the host in the source section (before "target:")
    val targetIdx = baseContent.indexOf("\ntarget:")
    val sourceSection = baseContent.substring(0, targetIdx)
    val rest = baseContent.substring(targetIdx)
    val newContent = sourceSection.replace("host: cassandra", s"host: ${version.dockerHost}") + rest

    val newFileName = baseConfigFile.replace("cassandra-", s"${version.dockerHost}-")
    Files.write(configDir.resolve(newFileName), newContent.getBytes)
    newFileName
  }
}
