name: Build Spark image
on:
  push:
    branches:
      - master
    paths:
      - 'dockerfiles/spark/**'
      - '.github/workflows/spark-image.yml'
      - 'Makefile'
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and push Spark image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Build and push Spark image to cache
        run: make spark-image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
